---
title: 'ESM 204: HW 4 Code'
author: "Larissa Neilson"
date: "5/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(ggpubr)
```

```{r}
# Read in the data
damage <- read_csv(here("data", "damages.csv")) %>% 
  clean_names()
warming <- read_csv(here("data", "warming.csv")) %>% 
  clean_names()
```

```{r}
# Visualize the data
ggplot(data = damage, aes(x = warming, y = damages)) + 
  geom_point() +
  theme_minimal()

# Fit simple linear regression model first to explore
damages_lm <- lm(damages ~ warming, data = damage)
summary(damages_lm)

damage_col <- damage %>% 
  mutate(warming2 = warming^2)

# Fit quadratic regression model
damages_quad <-lm(damages ~ warming + warming2, data = damage_col)
summary(damages_quad)

# How well does the model fit the data aka question 1
ggplot(data = damage_col, aes(x = warming, y = damages)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm",
              formula = y ~ x + I(x^2),
              size = 0.5) +
  labs(x = "Level of warming (ºC)", y = "Annual total damages ($)") +
  theme_minimal()

# Full quadratic equation:
# Damages = 1.95e+13(warming)^2 - 3.019e+12(warming) + 4.198e+12
# But in the HW it asks us to omit the intercept (4.198e+12)
# Interpretation: For every one unit of increase in warming, there will be 1.95e+13 more dollars in damages (I THINK... don't know how to accurately describe the terms in a quadratic function bc of the ^2)
```

```{r}
# Function with our quadratic equation
damage_function <- function(warming) {
  damages <- (19500000000000 * warming^2) - (3019000000000 * warming)
  return(damages)
}

# Test
damage_function(0.3022845)
```

```{r}
# Test, this should input the same # as the last test line but it's slightly off?
damage_function(warming[1, "warming_baseline"])

# This makes new column with the calculated damages using values from the warming_baseline column
warming$damage_base <- damage_function(warming$warming_baseline)
head(warming$damage_base)

# Question 2 plot (1)
ggplot(data = warming, aes(x = year, y = damage_base)) +
  geom_point() +
  labs(x = "Year", y = "Total damages ($)") +
  theme_minimal()

# Do the same with values from the warming_pulse column
warming$damage_pulse <- damage_function(warming$warming_pulse)
head(warming$damage_pulse)

# Question 2 plot (2)
ggplot(data = warming, aes(x = year, y = damage_pulse)) +
  geom_point() +
  labs(x = "Year", y = "Total damages ($)") +
  theme_minimal()
```

```{r}
warming_diff <- warming %>% 
  mutate(damage_diff = (damage_pulse - damage_base))

# Question 2 plot (3)
ggplot(data = warming_diff, aes(x = year, y = damage_diff)) +
  geom_point() +
  labs(x = "Year", y = "Difference in damage ($)") +
  theme_minimal()
```

